"""add cascade delete messages

Revision ID: f6ca4a845fc6
Revises: 50d4652a17d1
Create Date: 2025-11-19 17:53:25.835638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ca4a845fc6'
down_revision: Union[str, None] = '50d4652a17d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('message_chat_id_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_chat_id_fkey', 'message', 'chat', ['chat_id'], ['id'])
    op.alter_column('message', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
